<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class MBulog extends CI_Model
{

    public $table = 'bulog';
    public $id = 'id_bulog';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_bulog', $q);
	$this->db->or_like('id_stok_bulog', $q);
	$this->db->or_like('supply_point', $q);
	$this->db->or_like('kg', $q);
    $this->db->or_like('tgl', $q);
	$this->db->or_like('dokumentasi', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {

   //join tabel stok
    $this->db->select('b.*,s.keterangan,s.id_stok_bulog');
    $this->db->from('bulog b');
    $this->db->join('stok s', 's.id_stok_bulog = b.id_stok_bulog');
   

    $this->db->order_by('b.id_bulog', $this->order);
    $this->db->like('b.id_bulog', $q);
	$this->db->or_like('b.id_stok_bulog', $q);
	$this->db->or_like('b.supply_point', $q);
	$this->db->or_like('b.kg', $q);
    $this->db->or_like('b.tgl', $q);
	$this->db->or_like('b.dokumentasi', $q);
	$this->db->limit($limit, $start);
        return $this->db->get()->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file MBulog.php */
/* Location: ./application/models/MBulog.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-05-08 11:56:53 */
/* http://harviacode.com */