<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class MKabupaten extends CI_Model
{

    public $table = 'kabupaten';
    public $id = 'id_kabupaten';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_kabupaten', $q);
	$this->db->or_like('id_supply', $q);
	$this->db->or_like('nama_kabupaten', $q);
	$this->db->or_like('kg', $q);
	$this->db->or_like('tgl', $q);
	$this->db->or_like('dokumentasi', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {

        //join tabel Supply Point
    $this->db->select('k.*,sp.kabupaten');
    $this->db->from('kabupaten k');
    $this->db->join('supply_point sp', 'sp.id_supply = k.id_supply');


    $this->db->order_by('k.id_kabupaten', $this->order);
    $this->db->like('k.id_kabupaten', $q);
	$this->db->or_like('k.id_supply', $q);
	$this->db->or_like('k.nama_kabupaten', $q);
	$this->db->or_like('k.kg', $q);
	$this->db->or_like('k.tgl', $q);
	$this->db->or_like('k.dokumentasi', $q);
	$this->db->limit($limit, $start);
        return $this->db->get()->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file MKabupaten.php */
/* Location: ./application/models/MKabupaten.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-05-08 10:20:47 */
/* http://harviacode.com */