<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class MKantor extends CI_Model
{

    public $table = 'kantor';
    public $id = 'id_kantor';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_kantor', $q);
	$this->db->or_like('nopend', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('phone', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('kode_pos', $q);
	$this->db->or_like('nopend_kcu', $q);
	$this->db->or_like('regional', $q);
	$this->db->or_like('nopend_kprk', $q);
	$this->db->or_like('tipe_kantor', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_kantor', $q);
	$this->db->or_like('nopend', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('phone', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('kode_pos', $q);
	$this->db->or_like('nopend_kcu', $q);
	$this->db->or_like('regional', $q);
	$this->db->or_like('nopend_kprk', $q);
	$this->db->or_like('tipe_kantor', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file MKantor.php */
/* Location: ./application/models/MKantor.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-03-09 04:10:46 */
/* http://harviacode.com */