<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class MSupply_point extends CI_Model
{

    public $table = 'supply_point';
    public $id = 'id_supply';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_supply', $q);
    $this->db->or_like('id_bulog', $q);
	$this->db->or_like('kabupaten', $q);
	$this->db->or_like('kg', $q);
	$this->db->or_like('tgl', $q);
	$this->db->or_like('dokumentasi', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {

  //join tabel bulog
    $this->db->select('sp.*,b.supply_point');
    $this->db->from('supply_point sp');
    $this->db->join('bulog b', 'b.id_bulog = sp.id_bulog');
   



    $this->db->order_by('sp.id_supply', $this->order);
    $this->db->like('sp.id_supply', $q);
    $this->db->or_like('sp.id_bulog', $q);
	$this->db->or_like('sp.kabupaten', $q);
	$this->db->or_like('sp.kg', $q);
	$this->db->or_like('sp.tgl', $q);
	$this->db->or_like('sp.dokumentasi', $q);
	$this->db->limit($limit, $start);
        return $this->db->get()->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file MSupply_point.php */
/* Location: ./application/models/MSupply_point.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-05-04 04:43:05 */
/* http://harviacode.com */